name: deploy GCP Workspace

on: push

jobs:
  databricks-deployment:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:

      - uses: "actions/checkout@v4"
      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/697856052963/locations/global/workloadIdentityPools/gh-actions/providers/github-actions"
          service_account: sa-gh-actions@fe-dev-sandbox.iam.gserviceaccount.com

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        working-directory: tf
        run: terraform init

      - id: plan
        name: Terraform Plan
        working-directory: tf
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        working-directory: tf
        run: terraform apply -auto-approve -input=false
